// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToysAndGames.DbContext;

#nullable disable

namespace ToysAndGames.Migrations
{
    [DbContext(typeof(ToysAndGamesContext))]
    partial class ToysAndGamesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToysAndGames.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 12,
                            Company = "Mattel",
                            Description = "Doll",
                            Name = "Barbie",
                            Price = 25.99m
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 12,
                            Company = "Mattel",
                            Description = "Action figure",
                            Name = "Max Steel",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = 12,
                            Company = "Hasbro",
                            Description = "Action figure",
                            Name = "GIJoe",
                            Price = 14.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
